version: '3'
services:
  python3:
    image: python_chainer
    container_name : some_python3
    build: ./python
    ports:
      - 8080:8080
    volumes:
      - .:/root
    working_dir: "/root"
    tty: true
